import baseWorker from './index.js';

const DUAL_PATH = '/v1/ai/unified';
const MAX_CONTEXT = 12000;
const MAX_INSTRUCTION = 12000;
const MAX_RESPONSE = 12000;

function json(data, status, headers = {}) { return new Response(JSON.stringify(data), { status, headers: { 'content-type': 'application/json; charset=utf-8', ...headers } }); }
function auth(request, env) { const token = env.GATEWAY_READ_TOKEN; return Boolean(token) && (request.headers.get('Authorization') || '') === `Bearer ${token}`; }
function cors(request, env) { const origin = request.headers.get('Origin'); const allowed = new Set((env.GATEWAY_ALLOWED_ORIGINS || '').split(',').map(v => v.trim()).filter(Boolean)); if (!origin || !allowed.has(origin)) return {}; return { 'access-control-allow-origin': origin, 'access-control-allow-headers': 'authorization,content-type,x-request-id', 'access-control-allow-methods': 'GET,POST,OPTIONS', vary: 'Origin' }; }
async function runPeer(env, model, role, task) { const result = await env.AI.run(model, { messages: [{ role: 'system', content: `You are the ${role} Workers AI peer for PHAN THUAN XTRA. Use the supplied checkpoint as authoritative. Never invent evidence, credentials, deployment state, or tests. Never output secrets. Production mutation is disabled. Return concise, actionable engineering findings with VERIFIED FACTS separated from RECOMMENDATIONS.` }, { role: 'user', content: `TASK_ID: ${task.taskId}\nMODE: ${task.mode}\nCHECKPOINT:\n${task.context}\n\nINSTRUCTION:\n${task.instruction}` }], temperature: 0.1, max_tokens: 900 }); const response = typeof result?.response === 'string' ? result.response : JSON.stringify(result); return response.slice(0, 6000); }
async function runDual(env, task) { if (env.DUAL_AI_ENABLED === 'false') return { ok: false, error: 'dual_ai_disabled' }; if (!env.AI || typeof env.AI.run !== 'function') return { ok: false, error: 'cloudflare_workers_ai_not_configured' }; const deepModel = env.DUAL_AI_DEEP_MODEL || '@cf/nvidia/nemotron-3-120b-a12b'; const wideModel = env.DUAL_AI_WIDE_MODEL || '@cf/zai-org/glm-4.7-flash'; try { const wide = await runPeer(env, wideModel, 'WIDE dependency/regression scan', task); const deep = await runPeer(env, deepModel, 'DEEP root-cause/verification', { ...task, context: `${task.context}\n\nWIDE PEER FINDINGS (advisory, not evidence):\n${wide}`.slice(0, MAX_CONTEXT) }); const response = ['=== WIDE ===', wide, '=== DEEP ===', deep, '=== ARBITRATION ===', 'Compare both peer findings against the supplied checkpoint. Resolve conflicts conservatively: verified runtime evidence outranks AI inference; prefer the smallest safe next step; do not mutate production.'].join('\n\n').slice(0, MAX_RESPONSE); return { ok: true, engine: 'cloudflare-workers-ai', dual_workers_ai: true, isolated: true, execution: 'serialized', runtime_order: ['wide', 'deep'], models: { deep: deepModel, wide: wideModel }, production_mutation: false, peer_results: { wide, deep }, response }; } catch (error) { return { ok: false, error: 'dual_workers_ai_failed', detail: String(error?.message || error).slice(0, 500) }; } }
export default { async fetch(request, env) { const url = new URL(request.url); const headers = cors(request, env); if (url.pathname !== DUAL_PATH || request.method !== 'POST') return baseWorker.fetch(request, env); if (!auth(request, env)) return json({ ok: false, error: 'unauthorized' }, 401, headers); if (!(request.headers.get('content-type') || '').toLowerCase().includes('application/json')) return json({ ok: false, error: 'content_type_required' }, 415, headers); const body = await request.json().catch(() => null); if (!body || typeof body !== 'object' || Array.isArray(body)) return json({ ok: false, error: 'invalid_json' }, 400, headers); const allowed = new Set(['instruction', 'context', 'mode', 'task_id']); if (Object.keys(body).some(key => !allowed.has(key))) return json({ ok: false, error: 'unexpected_field' }, 400, headers); if (typeof body.instruction !== 'string' || !body.instruction.trim()) return json({ ok: false, error: 'instruction_required' }, 400, headers); if (body.instruction.length > MAX_INSTRUCTION) return json({ ok: false, error: 'instruction_too_long', max_length: MAX_INSTRUCTION }, 400, headers); if (body.context !== undefined && (typeof body.context !== 'string' || body.context.length > MAX_CONTEXT)) return json({ ok: false, error: 'invalid_context', max_length: MAX_CONTEXT }, 400, headers); const task = { taskId: typeof body.task_id === 'string' && body.task_id.trim() ? body.task_id.trim().slice(0, 200) : crypto.randomUUID(), instruction: body.instruction.trim(), context: typeof body.context === 'string' ? body.context : '', mode: typeof body.mode === 'string' ? body.mode : 'audit' }; const result = await runDual(env, task); if (!result.ok) return json({ ok: false, task_id: task.taskId, ...result }, 502, headers); return json({ ok: true, task_id: task.taskId, logical_agent: 'xtra-unified-ai', peer_roles: ['wide-workers-ai', 'deep-workers-ai'], engine: result.engine, dual_workers_ai: true, isolated: true, execution: result.execution, runtime_order: result.runtime_order, models: result.models, production_mutation: false, response: result.response, peer_results: result.peer_results }, 200, headers); } };
