import { saveCar, carImages } from "./vehicle-persistence.js";
import { analyzeVehicleImage } from "./vehicle-ai.js";
import { issueAdminToken, verifyAdminToken } from "./admin-auth.js";
import { verifyAdminPassword } from "./admin-password.js";
import { listPosts, getPost, savePost, deletePost } from "./post-persistence.js";

const SEC={"X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"strict-origin-when-cross-origin","Strict-Transport-Security":"max-age=31536000; includeSubDomains; preload"};
const json=(data,status=200,headers={})=>new Response(JSON.stringify(data),{status,headers:{"content-type":"application/json; charset=utf-8","cache-control":"no-store",...SEC,...headers}});
const text=(v,n)=>String(v??"").trim().slice(0,n); const num=v=>Number.isFinite(Number(v))?Number(v):0;
const STATUSES=new Set(["available","reserved","sold"]);
const AI_GATEWAY={gateway:{id:"default",skipCache:true,cacheTtl:60},extraHeaders:{"cf-aig-metadata":JSON.stringify({app:"phanthuanxtra",surface:"android-app-api"})}};
const auth=async(r,e)=>{const a=r.headers.get("Authorization")||"";const t=e.APP_API_TOKEN;if(t&&a.startsWith("Bearer ")&&a.slice(7)===t)return true;return (await verifyAdminToken(r,e)).ok};
const deny=()=>json({error:"Unauthorized"},401,{"WWW-Authenticate":"Bearer"}); async function body(r){return r.json().catch(()=>null)}
async function login(r,e){if(r.method!=="POST")return json({error:"Method Not Allowed"},405,{Allow:"POST"});const b=await body(r)||{};const password=String(b.password??"");if(!e.ADMIN_PASSWORD)return json({error:"Admin credentials chưa được cấu hình"},503);if(!(await verifyAdminPassword(e,password)))return json({error:"Sai mật khẩu"},401);const token=await issueAdminToken(e);if(!token)return json({error:"Không thể tạo phiên Admin"},503);return json({ok:true,token})}
const images=carImages;
function norm(c,imgs=[]){let features=[];try{features=JSON.parse(c.features_json||"[]")}catch{}return {...c,features,images:imgs,cover_image:c.cover_image||imgs.find(x=>x.is_cover)?.url||imgs[0]?.url||""}}
async function cars(r,e,carId){if(!e.DB)return json({error:"D1 chưa được kết nối"},503);if(carId){const c=await e.DB.prepare("SELECT * FROM cars WHERE id=?").bind(carId).first();if(!c)return json({error:"Không tìm thấy xe"},404);if(r.method==='GET')return json({car:norm(c,await images(e.DB,carId))});if(r.method==='DELETE'){await e.DB.prepare("DELETE FROM car_images WHERE car_id=?").bind(carId).run();const result=await e.DB.prepare("DELETE FROM cars WHERE id=?").bind(carId).run();if(Number(result?.meta?.changes||0)!==1)return json({error:"Không tìm thấy xe"},404);return json({ok:true,id:carId,deleted:true});}if(r.method!=='PUT')return json({error:"Method Not Allowed"},405,{Allow:"GET,PUT,DELETE"});const b=await body(r);const saved=await saveCar(e.DB,b||{},{id:carId,mode:"update",actor:"app-api"});if(!saved.ok)return json({error:saved.error},saved.status);return json({ok:true,id:saved.id,car:saved.car});}
if(r.method==='GET'){const u=new URL(r.url),q=text(u.searchParams.get('q'),120),status=text(u.searchParams.get('status'),30);if(status&&!STATUSES.has(status))return json({error:"Trạng thái xe không hợp lệ"},400);let sql="SELECT * FROM cars",args=[];const where=[];if(q){where.push("(id LIKE ? OR brand LIKE ? OR model LIKE ?)");const x=`%${q}%`;args.push(x,x,x)}if(status){where.push("status=?");args.push(status)}if(where.length)sql+=` WHERE ${where.join(' AND ')}`;sql+=" ORDER BY featured DESC,created_at DESC LIMIT 500";const rs=await e.DB.prepare(sql).bind(...args).all();return json({cars:await Promise.all((rs.results||[]).map(async c=>norm(c,await images(e.DB,c.id))))})}
if(r.method!=='POST')return json({error:"Method Not Allowed"},405,{Allow:"GET,POST"});const b=await body(r);const saved=await saveCar(e.DB,b||{},{id:b?.id,mode:"create",actor:"app-api"});if(!saved.ok)return json({error:saved.error},saved.status);return json({ok:true,id:saved.id,car:saved.car},201)}
async function leads(r,e){
  if(!e.DB)return json({error:"D1 chưa được kết nối"},503);
  if(r.method==='GET'){
    const u=new URL(r.url),q=text(u.searchParams.get('q'),120),status=text(u.searchParams.get('status'),30);
    const allowed=new Set(["new","contacted","qualified","won","lost"]); if(status&&!allowed.has(status))return json({error:"Trạng thái lead không hợp lệ"},400);
    let sql="SELECT * FROM leads",args=[],where=[]; if(q){where.push("(name LIKE ? OR phone LIKE ? OR car_id LIKE ? OR message LIKE ? OR note LIKE ?)");const x=`%${q}%`;args.push(x,x,x,x,x)} if(status){where.push("status=?");args.push(status)} if(where.length)sql+=" WHERE "+where.join(" AND "); sql+=" ORDER BY created_at DESC,id DESC LIMIT 500";
    const result=await e.DB.prepare(sql).bind(...args).all(); return json({leads:result.results||[],count:(result.results||[]).length,statuses:[...allowed]});
  }
  const b=await body(r),id=num(b?.id); if(!Number.isInteger(id)||id<1)return json({error:"ID lead không hợp lệ"},400);
  const allowed=new Set(["new","contacted","qualified","won","lost"]);
  if(r.method==='PUT'){const status=text(b.status||'new',30);if(!allowed.has(status))return json({error:"Trạng thái lead không hợp lệ"},400);const result=await e.DB.prepare("UPDATE leads SET status=?,note=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(status,text(b.note,3000),id).run();if(Number(result?.meta?.changes||0)!==1)return json({error:"Không tìm thấy lead"},404);return json({ok:true,id,status});}
  if(r.method==='DELETE'){const result=await e.DB.prepare("DELETE FROM leads WHERE id=?").bind(id).run();if(Number(result?.meta?.changes||0)!==1)return json({error:"Không tìm thấy lead"},404);return json({ok:true,id,deleted:true});}
  return json({error:"Method Not Allowed"},405,{Allow:"GET,PUT,DELETE"});
}
async function posts(r,e,postId){if(!e.DB)return json({error:"D1 chưa được kết nối"},503);const u=new URL(r.url);if(r.method==="GET"){if(postId){const p=await getPost(e.DB,postId);return p?json({post:p}):json({error:"Không tìm thấy bài viết"},404)}return json({posts:await listPosts(e.DB,{status:text(u.searchParams.get("status"),20),q:text(u.searchParams.get("q"),120),limit:u.searchParams.get("limit")||100})})}const b=await body(r);if(r.method==="POST"){const x=await savePost(e.DB,b||{},{mode:"create",actor:"android-app"});return json(x.ok?{ok:true,id:x.id,post:x.post}:{error:x.error},x.status)}if(r.method==="PUT"){const x=await savePost(e.DB,b||{},{id:postId,mode:"update",actor:"android-app"});return json(x.ok?{ok:true,id:x.id,post:x.post}:{error:x.error},x.status)}if(r.method==="DELETE"){const x=await deletePost(e.DB,postId,{actor:"android-app"});return json(x.ok?{ok:true,deleted:x.id}:{error:x.error},x.status)}return json({error:"Method Not Allowed"},405,{Allow:"GET,POST,PUT,DELETE"})}

async function upload(r,e){if(!e.MEDIA)return json({error:"MEDIA chưa được kết nối"},503);if(r.method!=='POST')return json({error:"Method Not Allowed"},405,{Allow:"POST"});const type=r.headers.get("content-type")||"application/octet-stream";if(!type.startsWith("image/"))return json({error:"Chỉ nhận image/*"},415);const len=Number(r.headers.get("content-length")||0);if(len>12*1024*1024)return json({error:"Ảnh vượt quá 12MB"},413);const bytes=await r.arrayBuffer();if(bytes.byteLength>12*1024*1024)return json({error:"Ảnh vượt quá 12MB"},413);const ext=(type.split('/')[1]||'jpeg').replace(/[^a-z0-9]/gi,'').slice(0,10)||'jpeg';const mediaId=crypto.randomUUID(),key=`app/${new Date().toISOString().slice(0,10)}/${mediaId}.${ext}`;await e.MEDIA.put(key,bytes,{httpMetadata:{contentType:type,cacheControl:"public,max-age=31536000,immutable"}});return json({ok:true,key,url:`/media/${encodeURIComponent(key)}`},201)}
async function assistant(r,e){
  if(r.method!=='POST')return json({error:"Method Not Allowed"},405,{Allow:"POST"});
  if(!e.AI)return json({error:"Workers AI chưa được kết nối"},503);
  const b=await body(r)||{},question=text(b.question,4000);
  if(!question)return json({error:"Câu hỏi trống"},400);
  let cars=[];
  if(e.DB){try{const q=await e.DB.prepare("SELECT id,brand,model,year,mileage,price,fuel,category,color,status,description FROM cars WHERE status <> 'hidden' ORDER BY featured DESC,created_at DESC LIMIT 40").all();cars=q.results||[]}catch{}}
  const system=`Bạn là XTRA APK Assistant cho PHAN THUẦN XTRA. Trả lời ngắn gọn bằng tiếng Việt. Chỉ dùng dữ liệu catalog được cung cấp cho câu hỏi về xe; không bịa giá, ODO, tình trạng hay option. Với tác vụ quản trị, chỉ hướng dẫn và tóm tắt; không tự ý thay đổi D1/R2 hay production. CATALOG: ${JSON.stringify(cars)}`;
  const models=["@cf/meta/llama-3.1-8b-instruct-fast","@cf/qwen/qwen3.8-27b","@cf/nvidia/nemotron-3-120b-a12b"];
  let last=null;
  for(const model of models){try{const out=await e.AI.run(model,{messages:[{role:"system",content:system},{role:"user",content:question}],temperature:.15,max_tokens:700},{...AI_GATEWAY,rejectIfBusy:true});const answer=text(out?.response??out?.choices?.[0]?.message?.content,8000);if(answer)return json({ok:true,answer,model});}catch(x){last=x;if(/3036|daily.*(?:allocation|quota)|10,?000.*neurons/i.test(String(x?.message||x)))break;}}
  console.error("app_ai_assistant",String(last?.message||last||"unknown"));
  return json({error:"AI Assistant tạm thời không khả dụng"},503);
}
async function sentiment(r,e){
  if(r.method!=='POST')return json({error:"Method Not Allowed"},405,{Allow:"POST"});
  if(!e.AI)return json({error:"Workers AI chưa được kết nối"},503);
  const b=await body(r)||{},input=text(b.text,2000);
  if(!input)return json({error:"Nội dung trống"},400);
  try{
    const out=await e.AI.run("@cf/huggingface/distilbert-sst-2-int8",{text:input},{gateway:{id:"default",skipCache:true},extraHeaders:{"cf-aig-metadata":JSON.stringify({app:"phanthuanxtra",surface:"android-sentiment"})}});
    return json({ok:true,model:"@cf/huggingface/distilbert-sst-2-int8",result:out});
  }catch(x){console.error("app_sentiment",String(x?.message||x));return json({error:"Sentiment AI tạm thời không khả dụng"},503)}
}
async function analyze(r,e){if(r.method!=='POST')return json({error:"Method Not Allowed"},405,{Allow:"POST"});const type=r.headers.get("content-type")||"image/jpeg";if(!type.startsWith("image/"))return json({error:"Chỉ nhận image/*"},415);const bytes=await r.arrayBuffer();if(bytes.byteLength>12*1024*1024)return json({error:"Ảnh vượt quá 12MB"},413);const caption=text(new URL(r.url).searchParams.get('caption'),2000);try{return json({ok:true,analysis:await analyzeVehicleImage(e,bytes,type,caption)})}catch(x){console.error("app_vehicle_analyze",String(x?.message||x));return json({error:"Vehicle AI không khả dụng"},503)}}
function decodeCarId(pathname){const raw=pathname.slice('/api/app/v1/cars/'.length);try{return decodeURIComponent(raw)}catch{return null}}
export async function handleAppApi(r,e){const u=new URL(r.url);if(!u.pathname.startsWith('/api/app/v1/'))return null;if(u.pathname==='/api/app/v1/health')return json({ok:true,service:'app-api',version:'1.1.0',timestamp:new Date().toISOString()});if(u.pathname==='/api/app/v1/login')return login(r,e);if(!(await auth(r,e)))return deny();if(!e.DB&&/^\/api\/app\/v1\/cars/.test(u.pathname))return json({error:"D1 chưa được kết nối"},503);if(u.pathname==='/api/app/v1/cars')return cars(r,e);if(u.pathname.startsWith('/api/app/v1/cars/')){const carId=decodeCarId(u.pathname);if(carId===null)return json({error:"ID xe không hợp lệ"},400);return cars(r,e,carId)}if(u.pathname==='/api/app/v1/leads')return leads(r,e);if(u.pathname==='/api/app/v1/posts')return posts(r,e);if(u.pathname.startsWith('/api/app/v1/posts/')){let id;try{id=decodeURIComponent(u.pathname.slice('/api/app/v1/posts/'.length))}catch{return json({error:'ID bài viết không hợp lệ'},400)}return posts(r,e,id)}if(u.pathname==='/api/app/v1/media')return upload(r,e);if(u.pathname==='/api/app/v1/assistant')return assistant(r,e);if(u.pathname==='/api/app/v1/vehicle/analyze')return analyze(r,e);if(u.pathname==='/api/app/v1/sentiment')return sentiment(r,e);if(u.pathname==='/api/app/v1/dashboard'&&r.method==='GET'){if(!e.DB)return json({error:"D1 chưa được kết nối"},503);const [carsN,leadsN,soldN,reservedN,newLeadsN]=await Promise.all([e.DB.prepare("SELECT COUNT(*) n FROM cars").first('n'),e.DB.prepare("SELECT COUNT(*) n FROM leads").first('n'),e.DB.prepare("SELECT COUNT(*) n FROM cars WHERE status='sold'").first('n'),e.DB.prepare("SELECT COUNT(*) n FROM cars WHERE status='reserved'").first('n'),e.DB.prepare("SELECT COUNT(*) n FROM leads WHERE status='new'").first('n')]);return json({stats:{cars:Number(carsN||0),leads:Number(leadsN||0),sold:Number(soldN||0),reserved:Number(reservedN||0),newLeads:Number(newLeadsN||0)}})}return json({error:"Not Found"},404)}