import { renderPostCard, displayText } from "./blog-cards.js";
import { listPosts,getPost } from "./post-persistence.js";
import { seoForPost } from "./seo-ai.js";
const SEC={"content-type":"application/json; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"};
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:SEC});
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const blogHead='<link rel="stylesheet" href="/style.css"><meta name="theme-color" content="#050706">';
function render(p,seo){const body=esc(p.content).replace(/\n/g,"<br>");return `<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(seo?.seo_title||p.title)} — PHAN THUẦN XTRA</title><meta name="description" content="${esc(seo?.seo_description||p.excerpt||p.title)}"><link rel="canonical" href="https://phanthuanxtra.com/blog/${encodeURIComponent(p.slug)}">${blogHead}</head><body class="blog-page"><main class="blog-shell"><a class="blog-back" href="/blog">← PHAN THUẦN XTRA / Tin tức</a><article class="blog-detail"><h1>${esc(p.title)}</h1><p class="blog-meta">${esc(displayText(p.category||"Tin tức"))} • ${esc(p.published_at||p.created_at||"")}</p>${p.cover_image?`<img class="blog-cover" src="${esc(p.cover_image)}" alt="${esc(p.title)}">`:""}<p class="blog-excerpt">${esc(p.excerpt||"")}</p><div class="blog-content">${body}</div></article></main></body></html>`}
export async function handleBlog(request,env){const u=new URL(request.url);if(!env.DB)return null;const db=env.DB.withSession?.("first-primary")||env.DB;if(u.pathname==="/api/blog/posts"&&request.method==="GET")return json({posts:await listPosts(db,{publicOnly:true,q:u.searchParams.get("q")||"",limit:u.searchParams.get("limit")||50})});if(u.pathname.startsWith("/api/blog/posts/")&&request.method==="GET"){const p=await getPost(db,decodeURIComponent(u.pathname.slice(16)),{publicOnly:true});return p?json({post:p}):json({error:"Not Found"},404)};if(u.pathname==="/blog"||u.pathname==="/blog/"){const posts=await listPosts(db,{publicOnly:true,limit:100});const cards=posts.map(p=>renderPostCard(p)).join("");return new Response(`<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Blog / Tin tức — PHAN THUẦN XTRA</title>${blogHead}</head><body class="blog-page"><main class="blog-shell"><a class="blog-back" href="/">← Trang chủ</a><p class="eyebrow">BLOG • PHAN THUẦN XTRA</p><h1>Bài viết mới nhất</h1><p class="blog-lead">Ô tô cao cấp • Phong cách sống • Hệ sinh thái AI</p><section class="blog-grid">${cards||"<p>Chưa có bài viết đã xuất bản.</p>"}</section></main></body></html>`,{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}})}if(u.pathname.startsWith("/blog/")&&request.method==="GET"){const p=await getPost(db,decodeURIComponent(u.pathname.slice(6)),{publicOnly:true});return p?new Response(render(p,await seoForPost(db,p.id)),{headers:{"content-type":"text/html; charset=utf-8","cache-control":"no-store","x-content-type-options":"nosniff"}}):new Response("Not Found",{status:404})}return null}
