const TEXT_MODELS=["@cf/zai-org/glm-4.7-flash","@cf/google/gemma-4-26b-a4b-it","@cf/nvidia/nemotron-3-120b-a12b","@cf/meta/llama-3.2-3b-instruct"];
const VISION_MODELS=["@cf/qwen/qwen3.8-27b","@cf/google/gemma-4-26b-a4b-it","@cf/meta/llama-3.2-11b-vision-instruct"];
const clean=(v,n=50000)=>String(v??"").trim().slice(0,n);
function parse(r){const v=r?.response??r?.choices?.[0]?.message?.content??r;if(typeof v==="object")return v;const s=clean(v);try{return JSON.parse(s)}catch{const m=s.match(/\{[\s\S]*\}/);if(m)return JSON.parse(m[0]);return{content:s}}}
function dataUrl(type,bytes){let s="";const a=new Uint8Array(bytes);for(let i=0;i<a.length;i+=32768)s+=String.fromCharCode(...a.subarray(i,Math.min(i+32768,a.length)));return `data:${type||"image/jpeg"};base64,${btoa(s)}`}
async function runFallback(env,models,input){const errors=[];for(const model of models){try{return{model,result:parse(await env.AI.run(model,input(model)))}}catch(e){errors.push({model,error:clean(e?.message||e,180)})}}const x=new Error("Workers AI models unavailable");x.diagnostics=errors;throw x}
export async function editorialPost(env,body={}){if(!env.AI)throw new Error("Workers AI binding AI is not configured");const source=clean(body.source||body.content||"",30000),instruction=clean(body.instruction||"Biên tập thành bài Blog/Tin tức chuyên nghiệp, chính xác, không bịa dữ kiện.",2000);if(!source)throw new Error("source là bắt buộc");const prompt=`Bạn là biên tập viên PHAN THUẦN XTRA. Viết tiếng Việt tự nhiên, sang trọng, hữu ích. Không bịa thông số, giá, nguồn hay sự kiện. Nếu dữ kiện thiếu thì giữ trung tính. ${instruction}\n\nNguồn:\n${source}\n\nChỉ trả JSON: {"title":"","excerpt":"","content":"","category":"Tin tức","tags":[""],"seo_title":"","seo_description":""}`;return runFallback(env,TEXT_MODELS,model=>({messages:[{role:"system",content:"Biên tập nội dung có kiểm chứng; chỉ trả JSON."},{role:"user",content:prompt}],max_tokens:1800,temperature:model.includes("glm-4.7")?.25:.2}))}
export async function analyzeEditorialImage(env,bytes,type="image/jpeg",instruction=""){if(!env.AI)throw new Error("Workers AI binding AI is not configured");const image=dataUrl(type,bytes),prompt=`Phân tích ảnh để hỗ trợ biên tập PHAN THUẦN XTRA. Không đoán danh tính, biển số, năm xe, giá hay thông số nếu không nhìn thấy chắc chắn. ${clean(instruction,1200)} Chỉ trả JSON: {"description":"","alt_text":"","objects":[],"suggested_caption":"","safety_notes":[]}`;return runFallback(env,VISION_MODELS,model=>model.includes("llama-3.2-11b")?{messages:[{role:"user",content:prompt}],image,max_tokens:800,temperature:0}:{messages:[{role:"user",content:[{type:"image_url",image_url:{url:image}},{type:"text",text:prompt}]}],max_tokens:800,temperature:0})}
export const editorialModelPolicy={text:TEXT_MODELS,vision:VISION_MODELS};
